#!/bin/sh

REMOTEHOST=wcsdev
REMOTEUSER=fortna
REMOTEPATH=/opt/SUNWappserver2_1/domains/domain1/data/webui
# Must match ScreenCapture_FileName in FPC
INFILEGLOB=fpcscreen*
# Use most recent
INFILE=`ls -tr ${INFILEGLOB} 2>/dev/null | tail -n 1`
TMPPHSFILE=tmpimage.phs
TMPBMPFILE=tmpimage.bmp
TMPPNGFILE=tmpimage.${HOSTNAME}.png
PNGFILE=fpcimage.latest.png
STAMPFILE=/tmp/$0.stamp
RELEASE=`uname -r | sed 's/\.//g'`

# Sleep for a second to offset from the image generation batch
sleep 1

NOW=`date -t`

# Got something to do?
if test -f "${INFILE}"
then
	chmod 666 ${INFILE}
	if [ 0${RELEASE} -ge 640 ]
	then
		# FPC produces bmp file directly
		mv ${INFILE} ${TMPBMPFILE}
	else
		# FPC produces phs file, convert to bmp
		# Set input file aside to avoid over-writes
		mv ${INFILE} ${TMPPHSFILE}
		# Create bitmap in temporary file since it takes a while
		phs-to-bmp ${TMPPHSFILE} > ${TMPBMPFILE}
	fi
	if test -f ${TMPBMPFILE}
	then
		# Convert to more compact png format
		rm -f ${TMPPNGFILE}*
		bmp2png -QO ${TMPPNGFILE} ${TMPBMPFILE}
		if test -f ${TMPPNGFILE}
		then
			# compare new to old, quit if no change
			# $?: 0=same, 1=differ, 2=missing file
			# NOTE: The PHS files have a timestamp, so will always differ
			# It takes longer to cmp the BMPs than to convert them to PNG
			# then cmp them!
			if test ! -f ${PNGFILE}
			then
				touch ${PNGFILE}
			fi
			cmp -s ${PNGFILE} ${TMPPNGFILE}
			if [ $? -eq 1 ]
			then
				# Send the file
				# Make sure pgp security is set up for ssh!
				scp -o BatchMode=yes -q ${TMPPNGFILE} ${REMOTEUSER}@${REMOTEHOST}:${REMOTEPATH}/${TMPPNGFILE}
				# Make output file available locally, avoid partial file reads
				chmod 666 ${TMPPNGFILE}
				mv ${TMPPNGFILE} ${PNGFILE}
				ssh -o BatchMode=yes ${REMOTEUSER}@${REMOTEHOST} mv ${REMOTEPATH}/${TMPPNGFILE} ${REMOTEPATH}/${PNGFILE}
				# Compute a quantized timestamp based on the rate that this script
				# gets executed.  This is done so multiple fail-over machines can
				# send the image, but only one will be processed per interval
				# This depends on the clocks being reasonably synchronized, via ntp
				if test -f ${STAMPFILE}; then
					OLDNOW=`cat ${STAMPFILE}`
					let QINT=${NOW}-${OLDNOW}
				else
					QINT=5
				fi
				if test ${QINT} -le 0; then
					QINT=5
				fi
				# Some integer math trickery to compute a floor value to the quantized interval
				let QTIME=${NOW}/${QINT}*${QINT}
				# Send the quantized time to the queue
				stompput ${REMOTEHOST} fpc pw "/topic/WCS.UI.VIEW.IMAGE" "" "${QTIME}"
#			else
#				echo "File has not changed"
			fi
#			echo "$0: Done. ${INFILE} -> ${PNGFILE}"
		fi
	fi
#else
#	echo "$0: Nothing to do."
fi
# Save the timestamp for the next round
echo ${NOW} > ${STAMPFILE}

# Clean up
rm -f ${INFILEGLOB} ${TMPPHSFILE} ${TMPBMPFILE} ${TMPPNGFILE}*
