driftfile /etc/ntp/ntp.drift

# act only as ntp client
restrict default nomodify nopeer noquery notrap
# allow the loopback address, for local ntpq access
restrict 127.0.0.1

#server 0.us.pool.ntp.org
#server 1.us.pool.ntp.org
#server 2.us.pool.ntp.org
#server us.pool.ntp.org
server 172.25.2.100
 
 
 
 
 
 
 
 
       
