;
; odbc.ini configuration for MyODBC and MyODBC 5.1 drivers
;
[ODBC Data Sources]
Fortna		= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
Information_schema		= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
Default		= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
myodbc3		= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)

[Fortna]
Driver		= /usr/local/odbc/lib/libmyodbc5.so
Description	= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
SERVER		= 172.19.46.61
PORT		=
USER		= root
Password	= rhel30
Database	= fortna
OPTION		= 3
SOCKET		= 
READTIMEOUT = 2
WRITETIMEOUT = 2
TRACE = off
TRACEFILE = /tmp/odbc_fortna.trace

[Information_schema]
Driver		= /usr/local/odbc/lib/libmyodbc5.so
Description	= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
SERVER		= 172.19.46.61
PORT		=
USER		= root
Password	= rhel30
Database	= information_schema
OPTION		= 3
SOCKET		= 
READTIMEOUT = 2
WRITETIMEOUT = 2
TRACE = off
TRACEFILE = /tmp/odbc_info.trace

[Default]
Driver		= /usr/local/odbc/lib/libmyodbc5.so
Description	= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
SERVER		= 172.19.46.61
PORT		=
USER		= root
Password	= rhel30
Database	= test
OPTION		= 3
SOCKET		= 
READTIMEOUT = 2
WRITETIMEOUT = 2
TRACE = off
TRACEFILE = /tmp/odbc_default.trace

[myodbc3]
Driver		= /usr/local/odbc/lib/libmyodbc5.so
Description	= MyODBC 5.1 Driver DSN (from /etc/odbc.ini)
SERVER		= 172.19.46.61
PORT		=
USER		= root
Password	= rhel30
Database	= myodbc3
OPTION		= 3
SOCKET		= 
READTIMEOUT = 2
WRITETIMEOUT = 2
TRACE = off
TRACEFILE = /tmp/odbc_myodbc3.trace
