const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  runRealMerge: (data) => ipcRenderer.invoke('run-real-merge', data),
  stageDemoMergedOutput: (data) => ipcRenderer.invoke('stage-demo-merged-output', data),
  saveDroppedFiles: (system, dropped) => ipcRenderer.invoke('save-dropped-files', system, dropped),
  readWorktreeFile: (system, filename) => ipcRenderer.invoke('read-worktree-file', system, filename),
  writeBranchMerge: (system, program, content) => ipcRenderer.invoke('write-branch-merge', system, program, content),
  extractPdfIo: (data) => ipcRenderer.invoke('extract-pdf-io', data),
  selectPdfFolder: () => ipcRenderer.invoke('select-pdf-folder'),
  selectL5xFolder: () => ipcRenderer.invoke('select-l5x-folder'),
  selectL5xFile: (data) => ipcRenderer.invoke('select-l5x-file', data),
  findL5xFile: (data) => ipcRenderer.invoke('find-l5x-file', data),
  discoverL5x: (data) => ipcRenderer.invoke('discover-l5x', data),
  listPdfsInFolder: (folderPath) => ipcRenderer.invoke('list-pdfs-in-folder', folderPath),
  selectAcadeFile: (defaultDir) => ipcRenderer.invoke('select-acade-file', defaultDir),
  findExportFile: (folder) => ipcRenderer.invoke('find-export-file', folder),
  extractAcadeIo: (data) => ipcRenderer.invoke('extract-acade-io', data),
  generateRoughProgram: (data) => ipcRenderer.invoke('generate-rough-program', data),
  loadIntakeProfiles: () => ipcRenderer.invoke('load-intake-profiles'),
  saveIntakeProfiles: (store) => ipcRenderer.invoke('save-intake-profiles', store),
  ensureIntakeProjectFolder: (data) => ipcRenderer.invoke('ensure-intake-project-folder', data),
  stageDemoIntakeFile: (data) => ipcRenderer.invoke('stage-demo-intake-file', data),
  loadIntakeCache: (data) => ipcRenderer.invoke('load-intake-cache', data),
  generateFactoryIoScene: (data) => ipcRenderer.invoke('generate-factory-io-scene', data),
  generateEmulate3dBindings: (data) => ipcRenderer.invoke('generate-emulate3d-bindings', data),
  generateEmulate3dScene: (data) => ipcRenderer.invoke('generate-emulate3d-scene', data),
  detectEmulate3d: () => ipcRenderer.invoke('detect-emulate3d'),
  launchEmulate3dBridge: (data) => ipcRenderer.invoke('launch-emulate3d-bridge', data),
  extractLayoutFromDxf: (data) => ipcRenderer.invoke('extract-layout-from-dxf', data),
  loadLayoutFiles: (data) => ipcRenderer.invoke('load-layout-files', data),
  saveLayoutFiles: (data) => ipcRenderer.invoke('save-layout-files', data),
  selectLayoutFiles: (data) => ipcRenderer.invoke('select-layout-files', data),
  buildSpatialLayout: (data) => ipcRenderer.invoke('build-spatial-layout', data),
  loadSpatialCache: (data) => ipcRenderer.invoke('load-spatial-cache', data),
  openSystemFolder: (data) => ipcRenderer.invoke('open-system-folder', data),
  openPath: (targetPath) => ipcRenderer.invoke('open-path', targetPath),
  getIntakeHealth: (data) => ipcRenderer.invoke('get-intake-health', data),
  prismListSites: () => ipcRenderer.invoke('prism-list-sites'),
  prismDeleteSite: (data) => ipcRenderer.invoke('prism-delete-site', data),
  prismCreateSite: (data) => ipcRenderer.invoke('prism-create-site', data),
  prismStageFile: (data) => ipcRenderer.invoke('prism-stage-file', data),
  prismStats: () => ipcRenderer.invoke('prism-stats'),
  prismIndex: (data) => ipcRenderer.invoke('prism-index', data),
  prismSearch: (data) => ipcRenderer.invoke('prism-search', data),
  prismContext: (data) => ipcRenderer.invoke('prism-context', data),
  prismSaveOutput: (data) => ipcRenderer.invoke('prism-save-output', data),
  prismOpenCorpus: (data) => ipcRenderer.invoke('prism-open-corpus', data),
  prismSelectFiles: (data) => ipcRenderer.invoke('prism-select-files', data),
  getPathForFile: (file) => {
    try {
      return webUtils.getPathForFile(file);
    } catch (_) {
      return file?.path || '';
    }
  },
});